# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spotnik < Formula
  desc "A terminal Spotify client for developers. Keyboard-driven, single binary."
  homepage "https://github.com/initgrep-apps/spotnik"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/initgrep-apps/spotnik/releases/download/v1.1.0/spotnik_1.1.0_darwin_amd64.tar.gz"
      sha256 "66c7321fe10ea9a0b5c3a6c13a82195ce09ff66028028f81a6199f21a1c5d99e"

      define_method(:install) do
        bin.install "spotnik"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/initgrep-apps/spotnik/releases/download/v1.1.0/spotnik_1.1.0_darwin_arm64.tar.gz"
      sha256 "5a6d0b7cd362ea801c52382f99cb9c2d44b98d0c855b005052e1a8de38a605c5"

      define_method(:install) do
        bin.install "spotnik"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/initgrep-apps/spotnik/releases/download/v1.1.0/spotnik_1.1.0_linux_amd64.tar.gz"
      sha256 "49e70770152ff20c05d38452ccdd78cf50f75e4d1e5f4dcda29633d36a0cf787"
      define_method(:install) do
        bin.install "spotnik"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/initgrep-apps/spotnik/releases/download/v1.1.0/spotnik_1.1.0_linux_arm64.tar.gz"
      sha256 "fce56268f5c8e81528f99f9f9325e394483225de4b4250db72b2e9aa2df499c2"
      define_method(:install) do
        bin.install "spotnik"
      end
    end
  end

  test do
    system "#{bin}/spotnik", "--version"
  end
end
